// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/swoq.proto

package swoq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartResult int32

const (
	StartResult_START_RESULT_OK                   StartResult = 0
	StartResult_START_RESULT_INTERNAL_ERROR       StartResult = 1
	StartResult_START_RESULT_UNKNOWN_USER         StartResult = 2
	StartResult_START_RESULT_INVALID_LEVEL        StartResult = 3
	StartResult_START_RESULT_QUEST_QUEUED         StartResult = 4
	StartResult_START_RESULT_QUEST_ALREADY_ACTIVE StartResult = 5
)

// Enum value maps for StartResult.
var (
	StartResult_name = map[int32]string{
		0: "START_RESULT_OK",
		1: "START_RESULT_INTERNAL_ERROR",
		2: "START_RESULT_UNKNOWN_USER",
		3: "START_RESULT_INVALID_LEVEL",
		4: "START_RESULT_QUEST_QUEUED",
		5: "START_RESULT_QUEST_ALREADY_ACTIVE",
	}
	StartResult_value = map[string]int32{
		"START_RESULT_OK":                   0,
		"START_RESULT_INTERNAL_ERROR":       1,
		"START_RESULT_UNKNOWN_USER":         2,
		"START_RESULT_INVALID_LEVEL":        3,
		"START_RESULT_QUEST_QUEUED":         4,
		"START_RESULT_QUEST_ALREADY_ACTIVE": 5,
	}
)

func (x StartResult) Enum() *StartResult {
	p := new(StartResult)
	*p = x
	return p
}

func (x StartResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_swoq_proto_enumTypes[0].Descriptor()
}

func (StartResult) Type() protoreflect.EnumType {
	return &file_proto_swoq_proto_enumTypes[0]
}

func (x StartResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartResult.Descriptor instead.
func (StartResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{0}
}

type ActResult int32

const (
	ActResult_ACT_RESULT_OK               ActResult = 0
	ActResult_ACT_RESULT_INTERNAL_ERROR   ActResult = 1
	ActResult_ACT_RESULT_UNKNOWN_GAME_ID  ActResult = 2
	ActResult_ACT_RESULT_MOVE_NOT_ALLOWED ActResult = 3
	ActResult_ACT_RESULT_UNKNOWN_ACTION   ActResult = 4
	ActResult_ACT_RESULT_GAME_FINISHED    ActResult = 5
)

// Enum value maps for ActResult.
var (
	ActResult_name = map[int32]string{
		0: "ACT_RESULT_OK",
		1: "ACT_RESULT_INTERNAL_ERROR",
		2: "ACT_RESULT_UNKNOWN_GAME_ID",
		3: "ACT_RESULT_MOVE_NOT_ALLOWED",
		4: "ACT_RESULT_UNKNOWN_ACTION",
		5: "ACT_RESULT_GAME_FINISHED",
	}
	ActResult_value = map[string]int32{
		"ACT_RESULT_OK":               0,
		"ACT_RESULT_INTERNAL_ERROR":   1,
		"ACT_RESULT_UNKNOWN_GAME_ID":  2,
		"ACT_RESULT_MOVE_NOT_ALLOWED": 3,
		"ACT_RESULT_UNKNOWN_ACTION":   4,
		"ACT_RESULT_GAME_FINISHED":    5,
	}
)

func (x ActResult) Enum() *ActResult {
	p := new(ActResult)
	*p = x
	return p
}

func (x ActResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_swoq_proto_enumTypes[1].Descriptor()
}

func (ActResult) Type() protoreflect.EnumType {
	return &file_proto_swoq_proto_enumTypes[1]
}

func (x ActResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActResult.Descriptor instead.
func (ActResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{1}
}

type DirectedAction int32

const (
	DirectedAction_DIRECTED_ACTION_NONE       DirectedAction = 0
	DirectedAction_DIRECTED_ACTION_MOVE_NORTH DirectedAction = 1
	DirectedAction_DIRECTED_ACTION_MOVE_EAST  DirectedAction = 2
	DirectedAction_DIRECTED_ACTION_MOVE_SOUTH DirectedAction = 3
	DirectedAction_DIRECTED_ACTION_MOVE_WEST  DirectedAction = 4
)

// Enum value maps for DirectedAction.
var (
	DirectedAction_name = map[int32]string{
		0: "DIRECTED_ACTION_NONE",
		1: "DIRECTED_ACTION_MOVE_NORTH",
		2: "DIRECTED_ACTION_MOVE_EAST",
		3: "DIRECTED_ACTION_MOVE_SOUTH",
		4: "DIRECTED_ACTION_MOVE_WEST",
	}
	DirectedAction_value = map[string]int32{
		"DIRECTED_ACTION_NONE":       0,
		"DIRECTED_ACTION_MOVE_NORTH": 1,
		"DIRECTED_ACTION_MOVE_EAST":  2,
		"DIRECTED_ACTION_MOVE_SOUTH": 3,
		"DIRECTED_ACTION_MOVE_WEST":  4,
	}
)

func (x DirectedAction) Enum() *DirectedAction {
	p := new(DirectedAction)
	*p = x
	return p
}

func (x DirectedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_swoq_proto_enumTypes[2].Descriptor()
}

func (DirectedAction) Type() protoreflect.EnumType {
	return &file_proto_swoq_proto_enumTypes[2]
}

func (x DirectedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectedAction.Descriptor instead.
func (DirectedAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{2}
}

type GameStatus int32

const (
	GameStatus_GAME_STATUS_ACTIVE               GameStatus = 0
	GameStatus_GAME_STATUS_FINISHED_SUCCESS     GameStatus = 1
	GameStatus_GAME_STATUS_FINISHED_TIMEOUT     GameStatus = 2
	GameStatus_GAME_STATUS_FINISHED_NO_PROGRESS GameStatus = 3
	GameStatus_GAME_STATUS_FINISHED_PLAYER_DIED GameStatus = 4
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_STATUS_ACTIVE",
		1: "GAME_STATUS_FINISHED_SUCCESS",
		2: "GAME_STATUS_FINISHED_TIMEOUT",
		3: "GAME_STATUS_FINISHED_NO_PROGRESS",
		4: "GAME_STATUS_FINISHED_PLAYER_DIED",
	}
	GameStatus_value = map[string]int32{
		"GAME_STATUS_ACTIVE":               0,
		"GAME_STATUS_FINISHED_SUCCESS":     1,
		"GAME_STATUS_FINISHED_TIMEOUT":     2,
		"GAME_STATUS_FINISHED_NO_PROGRESS": 3,
		"GAME_STATUS_FINISHED_PLAYER_DIED": 4,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_swoq_proto_enumTypes[3].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_proto_swoq_proto_enumTypes[3]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{3}
}

type Tile int32

const (
	Tile_TILE_UNKNOWN Tile = 0
	Tile_TILE_EMPTY   Tile = 1
	Tile_TILE_PLAYER  Tile = 2
	Tile_TILE_WALL    Tile = 3
	Tile_TILE_EXIT    Tile = 4
)

// Enum value maps for Tile.
var (
	Tile_name = map[int32]string{
		0: "TILE_UNKNOWN",
		1: "TILE_EMPTY",
		2: "TILE_PLAYER",
		3: "TILE_WALL",
		4: "TILE_EXIT",
	}
	Tile_value = map[string]int32{
		"TILE_UNKNOWN": 0,
		"TILE_EMPTY":   1,
		"TILE_PLAYER":  2,
		"TILE_WALL":    3,
		"TILE_EXIT":    4,
	}
)

func (x Tile) Enum() *Tile {
	p := new(Tile)
	*p = x
	return p
}

func (x Tile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tile) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_swoq_proto_enumTypes[4].Descriptor()
}

func (Tile) Type() protoreflect.EnumType {
	return &file_proto_swoq_proto_enumTypes[4]
}

func (x Tile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tile.Descriptor instead.
func (Tile) EnumDescriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{4}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         *int32                 `protobuf:"varint,2,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Seed          *int32                 `protobuf:"varint,3,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_swoq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartRequest) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *StartRequest) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

type StartResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Result          StartResult            `protobuf:"varint,1,opt,name=result,proto3,enum=Swoq.Interface.StartResult" json:"result,omitempty"`
	GameId          *string                `protobuf:"bytes,2,opt,name=gameId,proto3,oneof" json:"gameId,omitempty"`
	MapWidth        *int32                 `protobuf:"varint,3,opt,name=mapWidth,proto3,oneof" json:"mapWidth,omitempty"`
	MapHeight       *int32                 `protobuf:"varint,4,opt,name=mapHeight,proto3,oneof" json:"mapHeight,omitempty"`
	VisibilityRange *int32                 `protobuf:"varint,5,opt,name=visibilityRange,proto3,oneof" json:"visibilityRange,omitempty"`
	State           *State                 `protobuf:"bytes,6,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Seed            *int32                 `protobuf:"varint,7,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_swoq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetResult() StartResult {
	if x != nil {
		return x.Result
	}
	return StartResult_START_RESULT_OK
}

func (x *StartResponse) GetGameId() string {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return ""
}

func (x *StartResponse) GetMapWidth() int32 {
	if x != nil && x.MapWidth != nil {
		return *x.MapWidth
	}
	return 0
}

func (x *StartResponse) GetMapHeight() int32 {
	if x != nil && x.MapHeight != nil {
		return *x.MapHeight
	}
	return 0
}

func (x *StartResponse) GetVisibilityRange() int32 {
	if x != nil && x.VisibilityRange != nil {
		return *x.VisibilityRange
	}
	return 0
}

func (x *StartResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StartResponse) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

type ActRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Action        *DirectedAction        `protobuf:"varint,2,opt,name=action,proto3,enum=Swoq.Interface.DirectedAction,oneof" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRequest) Reset() {
	*x = ActRequest{}
	mi := &file_proto_swoq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRequest) ProtoMessage() {}

func (x *ActRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRequest.ProtoReflect.Descriptor instead.
func (*ActRequest) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{2}
}

func (x *ActRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ActRequest) GetAction() DirectedAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return DirectedAction_DIRECTED_ACTION_NONE
}

type ActResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        ActResult              `protobuf:"varint,1,opt,name=result,proto3,enum=Swoq.Interface.ActResult" json:"result,omitempty"`
	State         *State                 `protobuf:"bytes,2,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActResponse) Reset() {
	*x = ActResponse{}
	mi := &file_proto_swoq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActResponse) ProtoMessage() {}

func (x *ActResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActResponse.ProtoReflect.Descriptor instead.
func (*ActResponse) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{3}
}

func (x *ActResponse) GetResult() ActResult {
	if x != nil {
		return x.Result
	}
	return ActResult_ACT_RESULT_OK
}

func (x *ActResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Status        GameStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=Swoq.Interface.GameStatus" json:"status,omitempty"`
	PlayerState   *PlayerState           `protobuf:"bytes,4,opt,name=playerState,proto3,oneof" json:"playerState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_proto_swoq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *State) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *State) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_ACTIVE
}

func (x *State) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Surroundings  []Tile                 `protobuf:"varint,2,rep,packed,name=surroundings,proto3,enum=Swoq.Interface.Tile" json:"surroundings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_swoq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetSurroundings() []Tile {
	if x != nil {
		return x.Surroundings
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_swoq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{6}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Used by the ReplaySaver and ReplayViewer
type ReplayHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	DateTime      string                 `protobuf:"bytes,2,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayHeader) Reset() {
	*x = ReplayHeader{}
	mi := &file_proto_swoq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayHeader) ProtoMessage() {}

func (x *ReplayHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swoq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayHeader.ProtoReflect.Descriptor instead.
func (*ReplayHeader) Descriptor() ([]byte, []int) {
	return file_proto_swoq_proto_rawDescGZIP(), []int{7}
}

func (x *ReplayHeader) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReplayHeader) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

var File_proto_swoq_proto protoreflect.FileDescriptor

const file_proto_swoq_proto_rawDesc = "" +
	"\n" +
	"\x10proto/swoq.proto\x12\x0eSwoq.Interface\"m\n" +
	"\fStartRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\x05level\x18\x02 \x01(\x05H\x00R\x05level\x88\x01\x01\x12\x17\n" +
	"\x04seed\x18\x03 \x01(\x05H\x01R\x04seed\x88\x01\x01B\b\n" +
	"\x06_levelB\a\n" +
	"\x05_seed\"\xec\x02\n" +
	"\rStartResponse\x123\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1b.Swoq.Interface.StartResultR\x06result\x12\x1b\n" +
	"\x06gameId\x18\x02 \x01(\tH\x00R\x06gameId\x88\x01\x01\x12\x1f\n" +
	"\bmapWidth\x18\x03 \x01(\x05H\x01R\bmapWidth\x88\x01\x01\x12!\n" +
	"\tmapHeight\x18\x04 \x01(\x05H\x02R\tmapHeight\x88\x01\x01\x12-\n" +
	"\x0fvisibilityRange\x18\x05 \x01(\x05H\x03R\x0fvisibilityRange\x88\x01\x01\x120\n" +
	"\x05state\x18\x06 \x01(\v2\x15.Swoq.Interface.StateH\x04R\x05state\x88\x01\x01\x12\x17\n" +
	"\x04seed\x18\a \x01(\x05H\x05R\x04seed\x88\x01\x01B\t\n" +
	"\a_gameIdB\v\n" +
	"\t_mapWidthB\f\n" +
	"\n" +
	"_mapHeightB\x12\n" +
	"\x10_visibilityRangeB\b\n" +
	"\x06_stateB\a\n" +
	"\x05_seed\"l\n" +
	"\n" +
	"ActRequest\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\tR\x06gameId\x12;\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1e.Swoq.Interface.DirectedActionH\x00R\x06action\x88\x01\x01B\t\n" +
	"\a_action\"|\n" +
	"\vActResponse\x121\n" +
	"\x06result\x18\x01 \x01(\x0e2\x19.Swoq.Interface.ActResultR\x06result\x120\n" +
	"\x05state\x18\x02 \x01(\v2\x15.Swoq.Interface.StateH\x00R\x05state\x88\x01\x01B\b\n" +
	"\x06_state\"\xb9\x01\n" +
	"\x05State\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.Swoq.Interface.GameStatusR\x06status\x12B\n" +
	"\vplayerState\x18\x04 \x01(\v2\x1b.Swoq.Interface.PlayerStateH\x00R\vplayerState\x88\x01\x01B\x0e\n" +
	"\f_playerState\"}\n" +
	"\vPlayerState\x124\n" +
	"\bposition\x18\x01 \x01(\v2\x18.Swoq.Interface.PositionR\bposition\x128\n" +
	"\fsurroundings\x18\x02 \x03(\x0e2\x14.Swoq.Interface.TileR\fsurroundings\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"F\n" +
	"\fReplayHeader\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bdateTime\x18\x02 \x01(\tR\bdateTime*\xc8\x01\n" +
	"\vStartResult\x12\x13\n" +
	"\x0fSTART_RESULT_OK\x10\x00\x12\x1f\n" +
	"\x1bSTART_RESULT_INTERNAL_ERROR\x10\x01\x12\x1d\n" +
	"\x19START_RESULT_UNKNOWN_USER\x10\x02\x12\x1e\n" +
	"\x1aSTART_RESULT_INVALID_LEVEL\x10\x03\x12\x1d\n" +
	"\x19START_RESULT_QUEST_QUEUED\x10\x04\x12%\n" +
	"!START_RESULT_QUEST_ALREADY_ACTIVE\x10\x05*\xbb\x01\n" +
	"\tActResult\x12\x11\n" +
	"\rACT_RESULT_OK\x10\x00\x12\x1d\n" +
	"\x19ACT_RESULT_INTERNAL_ERROR\x10\x01\x12\x1e\n" +
	"\x1aACT_RESULT_UNKNOWN_GAME_ID\x10\x02\x12\x1f\n" +
	"\x1bACT_RESULT_MOVE_NOT_ALLOWED\x10\x03\x12\x1d\n" +
	"\x19ACT_RESULT_UNKNOWN_ACTION\x10\x04\x12\x1c\n" +
	"\x18ACT_RESULT_GAME_FINISHED\x10\x05*\xa8\x01\n" +
	"\x0eDirectedAction\x12\x18\n" +
	"\x14DIRECTED_ACTION_NONE\x10\x00\x12\x1e\n" +
	"\x1aDIRECTED_ACTION_MOVE_NORTH\x10\x01\x12\x1d\n" +
	"\x19DIRECTED_ACTION_MOVE_EAST\x10\x02\x12\x1e\n" +
	"\x1aDIRECTED_ACTION_MOVE_SOUTH\x10\x03\x12\x1d\n" +
	"\x19DIRECTED_ACTION_MOVE_WEST\x10\x04*\xb4\x01\n" +
	"\n" +
	"GameStatus\x12\x16\n" +
	"\x12GAME_STATUS_ACTIVE\x10\x00\x12 \n" +
	"\x1cGAME_STATUS_FINISHED_SUCCESS\x10\x01\x12 \n" +
	"\x1cGAME_STATUS_FINISHED_TIMEOUT\x10\x02\x12$\n" +
	" GAME_STATUS_FINISHED_NO_PROGRESS\x10\x03\x12$\n" +
	" GAME_STATUS_FINISHED_PLAYER_DIED\x10\x04*W\n" +
	"\x04Tile\x12\x10\n" +
	"\fTILE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"TILE_EMPTY\x10\x01\x12\x0f\n" +
	"\vTILE_PLAYER\x10\x02\x12\r\n" +
	"\tTILE_WALL\x10\x03\x12\r\n" +
	"\tTILE_EXIT\x10\x042\x93\x01\n" +
	"\vGameService\x12D\n" +
	"\x05Start\x12\x1c.Swoq.Interface.StartRequest\x1a\x1d.Swoq.Interface.StartResponse\x12>\n" +
	"\x03Act\x12\x1a.Swoq.Interface.ActRequest\x1a\x1b.Swoq.Interface.ActResponseb\x06proto3"

var (
	file_proto_swoq_proto_rawDescOnce sync.Once
	file_proto_swoq_proto_rawDescData []byte
)

func file_proto_swoq_proto_rawDescGZIP() []byte {
	file_proto_swoq_proto_rawDescOnce.Do(func() {
		file_proto_swoq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swoq_proto_rawDesc), len(file_proto_swoq_proto_rawDesc)))
	})
	return file_proto_swoq_proto_rawDescData
}

var file_proto_swoq_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_swoq_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_swoq_proto_goTypes = []any{
	(StartResult)(0),      // 0: Swoq.Interface.StartResult
	(ActResult)(0),        // 1: Swoq.Interface.ActResult
	(DirectedAction)(0),   // 2: Swoq.Interface.DirectedAction
	(GameStatus)(0),       // 3: Swoq.Interface.GameStatus
	(Tile)(0),             // 4: Swoq.Interface.Tile
	(*StartRequest)(nil),  // 5: Swoq.Interface.StartRequest
	(*StartResponse)(nil), // 6: Swoq.Interface.StartResponse
	(*ActRequest)(nil),    // 7: Swoq.Interface.ActRequest
	(*ActResponse)(nil),   // 8: Swoq.Interface.ActResponse
	(*State)(nil),         // 9: Swoq.Interface.State
	(*PlayerState)(nil),   // 10: Swoq.Interface.PlayerState
	(*Position)(nil),      // 11: Swoq.Interface.Position
	(*ReplayHeader)(nil),  // 12: Swoq.Interface.ReplayHeader
}
var file_proto_swoq_proto_depIdxs = []int32{
	0,  // 0: Swoq.Interface.StartResponse.result:type_name -> Swoq.Interface.StartResult
	9,  // 1: Swoq.Interface.StartResponse.state:type_name -> Swoq.Interface.State
	2,  // 2: Swoq.Interface.ActRequest.action:type_name -> Swoq.Interface.DirectedAction
	1,  // 3: Swoq.Interface.ActResponse.result:type_name -> Swoq.Interface.ActResult
	9,  // 4: Swoq.Interface.ActResponse.state:type_name -> Swoq.Interface.State
	3,  // 5: Swoq.Interface.State.status:type_name -> Swoq.Interface.GameStatus
	10, // 6: Swoq.Interface.State.playerState:type_name -> Swoq.Interface.PlayerState
	11, // 7: Swoq.Interface.PlayerState.position:type_name -> Swoq.Interface.Position
	4,  // 8: Swoq.Interface.PlayerState.surroundings:type_name -> Swoq.Interface.Tile
	5,  // 9: Swoq.Interface.GameService.Start:input_type -> Swoq.Interface.StartRequest
	7,  // 10: Swoq.Interface.GameService.Act:input_type -> Swoq.Interface.ActRequest
	6,  // 11: Swoq.Interface.GameService.Start:output_type -> Swoq.Interface.StartResponse
	8,  // 12: Swoq.Interface.GameService.Act:output_type -> Swoq.Interface.ActResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_swoq_proto_init() }
func file_proto_swoq_proto_init() {
	if File_proto_swoq_proto != nil {
		return
	}
	file_proto_swoq_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_swoq_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_swoq_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_swoq_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_swoq_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swoq_proto_rawDesc), len(file_proto_swoq_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_swoq_proto_goTypes,
		DependencyIndexes: file_proto_swoq_proto_depIdxs,
		EnumInfos:         file_proto_swoq_proto_enumTypes,
		MessageInfos:      file_proto_swoq_proto_msgTypes,
	}.Build()
	File_proto_swoq_proto = out.File
	file_proto_swoq_proto_goTypes = nil
	file_proto_swoq_proto_depIdxs = nil
}
