name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish win-x64
      run: dotnet publish -r win-x64 --sc --no-restore
    - name: Publish linux-x64
      run: dotnet publish -r linux-x64 --sc --no-restore
