name: .NET

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.201
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish builds
      run: |
        dotnet publish -r win-x64 --sc --no-restore
        dotnet publish -r linux-x64 --sc --no-restore
    - name: Upload artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: ReplayViewer
        path: |
          ReplayViewer/bin/Release/net9.0/win-x64/publish/ReplayViewer-win-x64.zip
          ReplayViewer/bin/Release/net9.0/win-x64/publish/ReplayViewer-linux-x64.zip
